# Inch documentation coverage analysis
files:
  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - models/**/*.rb
    - services/**/*.rb
    - intents/**/*.rb
    - db/**/*.rb
    - config/**/*.rb
    - *.rb
    
  # define files excluded from the analysis (defaults to [])
  excluded:
    - vendor/**/*.rb
    - spec/**/*.rb
