checks:
      ruby:
        code_rating: true
        duplicate_code: true    
build:
    dependencies:
        before:
            - export PGPASSWORD=scrutinizer; psql -h 127.0.0.1 -c 'CREATE DATABASE mental_health_test;' -U scrutinizer
            - export PGPASSWORD=scrutinizer; psql -h 127.0.0.1 -d mental_health_test -c "CREATE USER mental WITH PASSWORD 'health';" -U scrutinizer
    environment:
        # Languages
        ruby: 2.4.2
     
        # Various pre-installed services that can be configured.
        postgresql: true
    tests:
        override:
            -
                command: 'bundle exec rake spec'
                environment:
                    'SCRUTINIZER_CC_FILE': 'my-coverage'
                coverage:
                    file: 'my-coverage'
                    format: 'rb-cc'
