checks:
      ruby:
        code_rating: true
        duplicate_code: true
        
build:
    environment:
        # Any environment variables we should set for you.
        variables:
   
        # Languages
        ruby:                     "2.3.1"
     
        # Various pre-installed services that can be configured.
        postgresql:           true
     