checks:
      ruby:
        code_rating: true
        duplicate_code: true
        
build:
    environment:
        # Languages
        ruby: 2.4.2
     
        # Various pre-installed services that can be configured.
        postgresql: true
     