language: ruby
rvm:
  - 2.4.1

before_script:
  - psql -c 'create database mental_health_test;' -U postgres
  - psql -c "CREATE USER mental WITH PASSWORD 'health';" -U postgres

script:
  - RACK_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake

addons:
  postgresql: "9.6"

deploy: 
  skip_cleanup: true
