language: ruby
rvm:
  - 2.4.3

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER mental WITH PASSWORD 'health';" -U postgres

addons:
  postgresql: "9.5"
