sudo: false
language: ruby
rvm:
  - 2.4.1
  - 2.3

before_script:
  - psql -c 'CREATE DATABASE mental_health_test;' -U postgres
  - psql -c "CREATE USER mental WITH PASSWORD 'health';" -U postgres

script:
  - RACK_ENV=test bundle exec rake db:migrate
  - RACK_ENV=test bundle exec rake spec
  - bundle exec rake bundle:audit
  
addons:
  postgresql: "9.6"
