sudo: false
language: ruby
rvm:
  - 2.5.0
  - 2.4.3

before_script:
  - psql -c 'CREATE DATABASE mental_health_test;' -U postgres
  - psql -c "CREATE USER mental WITH PASSWORD 'health';" -U postgres
  - sh -e /etc/init.d/xvfb start

after_script:
  - sh -e /ext/init.d/xvfb stop

# ensure bundle does not install docs
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - cp -p Gemfile.lock Gemfile.lock.org

script:
  - RACK_ENV=test bundle exec rake db:migrate
  - RACK_ENV=test bundle exec rake spec
  - bundle exec rake bundle:audit
  - bundle exec rubocop 
  - bundle exec travis_check_rubies
  - cp -p Gemfile.lock.org Gemfile.lock
  
addons:
  postgresql: "9.6"

bundler_args: 
  --without development production

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - RACK_ENV=test
    - DISPLAY=":99.0"

cache: bundler
