branch-defaults:
  master:
    environment: mental-test-dev
    group_suffix: null
global:
  application_name: mental-test
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.4 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
