development:
  adapter: postgresql
  encoding: unicode
  database: mental_health
  pool: 2
  username: mental
  password: health

test:
  adapter: postgresql
  encoding: unicode
  database: mental_health_test
  pool: 2
  username: mental
  password: health

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
