development:
  adapter: postgresql
  encoding: unicode
  database: mental_health
  pool: 2
  username: mental
  password: health

test:
  adapter: postgresql
  encoding: unicode
  database: mental_health_test
  pool: 2
  username: mental
  password: health

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: mental_health
  username: mental
  password: Welcome!1
