default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: mental_health
  pool: 2
  username: mental
  password: health

test:
  <<: *default
  database: mental_health_test
  pool: 2
  username: mental
  password: health

production:
  <<: *default
  database: mentalhealth
  username: mentalhealth
  password: <%= ENV['DATABASE_PAZSSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
  connect_timeout: 1
  checkout_timeout: 5
  variables:
    statement_timeout: 5000 # ms
