development:
  adapter: postgresql
  encoding: unicode
  database: mental_health
  pool: 2
  username: mental
  password: health

test:
  adapter: postgresql
  encoding: unicode
  database: mental_health_test
  pool: 2
  username: mental
  password: health

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  connect_timeout: 1
  checkout_timeout: 5
  variables:
    statement_timeout: 5000 # ms
