development:
  adapter: postgresql
  encoding: unicode
  database: mental_health
  pool: 2
  username: mental
  password: health

test:
  adapter: postgresql
  encoding: unicode
  database: mental_health
  pool: 2
  username: mental
  password: health

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>