# frozen_string_literal: true

require_relative 'alexa_help'
require_relative 'application_record'
require_relative 'assessment'
require_relative 'assessment_instrument'
require_relative 'choice'
require_relative 'instrument'
require_relative 'item'
require_relative 'rating_scale'
require_relative 'response'
require_relative 'survey'
require_relative 'user'
require_relative 'user_survey'
require_relative 'visit'
